name: Publish

on:
  release:
    types: [published]
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.*
    - name: Install dependencies
      run: dotnet restore HappyCRappy.sln
      
    - name: Build
      run: dotnet build HappyCRappy.sln -c Release --no-restore
      
    - name: Test
      run: dotnet test HappyCRappy.sln -c Release --no-build
      
    - name: Publish
      #run: dotnet publish "HappyCRappy/HappyCRappy.csproj" --configuration Release -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true
      run: dotnet publish "HappyCRappy/HappyCRappy.csproj" --configuration Release -p:PublishSingleFile=false
      
    - name: Archive Release
      run: |
        powershell Compress-Archive HappyCRappy/bin/Release/net7.0-windows/publish/* "HappyCRappy_${{ github.event.release.tag_name }}.zip"
    - name: Publish HappyCRappy to Github
      uses: svenstaro/upload-release-action@v2
      with:
        file: "HappyCRappy_${{ github.event.release.tag_name }}.zip"
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.event.release.tag_name }}
